apiVersion: 1
datasources:
  - name: Experiments
    uid: experiment-postgres
    type: postgres
    access: proxy
    url: experiment-db:5432
    user: grafana_reader
    secureJsonData:
      password: $GRAFANA_DB_READ_PASSWORD
    jsonData:
      database: experiments
      sslmode: disable
      postgresVersion: 1400
      timescaledb: false
    isDefault: true
